---
language: java

jdk:
  - openjdk8
  - openjdk11

addons:
  sonarcloud:
    organization: "adorsys"
    token: ${SONAR_TOKEN}

git:
  submodules: false

cache:
  timeout: 1000
  directories:
    - "$HOME/.m2"

install:
  - mvn --version

before_script:
  - mvn --version
  - echo "TRAVIS_JDK_VERSION is $TRAVIS_JDK_VERSION"

script:
  - env BUILD_NUMBER=$TRAVIS_BUILD_ID /bin/bash ./scripts/set_xs2a_connector_version_in_swagger.sh
  - MAVEN_OPTS="-Dlogging.level.root=warn -Dlogging.level.org.springframework.boot=warn -Dlogging.level.org.springframework.test=warn -Dlogging.level.org.hibernate=warn -Dlogging.level.de.adorsys=warn"
  - export MAVEN_OPTS
  - mvn -B -V clean install pmd:check || travis_terminate 1
  # JavaDocs are broken in Java 11 and fixed only in Java 12 : https://bugs.openjdk.java.net/browse/JDK-8212233
  - if [ $TRAVIS_JDK_VERSION == openjdk8 ]; then mvn -B -V javadoc:javadoc; fi || travis_terminate 1
  # Sonar analysis shall be run only for one version of Java
  - if [ $TRAVIS_JDK_VERSION == openjdk8 ]; then mvn -B -V sonar:sonar -Dsonar.projectKey=adorsys_xs2a; fi || travis_terminate 1
  - docker run -it --rm -v $PWD:/src -w /src -u $(id -u ${USER}):$(id -g ${USER}) adorsys/arc42-tools
    sh -c "make pages" || travis_terminate 1

before_deploy:
  - echo $GPG_SECRET_KEY | base64 --decode | $GPG_EXECUTABLE --import || true
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust || true

deploy:
  - cleanup: false
    provider: script
    script: mvn --settings scripts/mvn-release-settings.xml -Prelease -Dlogging.level.root=warn -Dlogging.level.org.springframework.boot=warn 
      -Dlogging.level.org.springframework.test=warn -Dlogging.level.org.hibernate=warn -Dlogging.level.de.adorsys=warn -DskipTests -B
      -U deploy || travis_terminate 1
    on:
      repo: adorsys/xs2a
      all_branches: true
      condition: |-
        ( ( $TRAVIS_TAG =~ ^([[:digit:]]+\.)+[[:digit:]]+(-(RC)?[[:digit:]]+)?([\.-]([[:digit:]]+\.)+[[:digit:]]+(-[[:digit:]]+)?)?$
          || "$TRAVIS_BRANCH" = "develop" )
        && "$TRAVIS_JDK_VERSION" = "openjdk8" )
  - provider: pages
    cleanup: false
    github-token: "$GITHUB_PAGES_TOKEN"
    keep-history: false
    local-dir: pages/html
    on:
      branch: develop
      condition: ( "$TRAVIS_JDK_VERSION" = "openjdk8" )
