{{ if .Values.uiapp.enabled }}
---
apiVersion: v1
kind: Service
metadata:
{{- with .Values.uiapp.serviceAnnotations }}
   annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ template "psd2.fullname" . }}-uiapp
  labels:
{{ include "psd2.labels" . | indent 4 }}
    component: uiapp
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
{{ include "psd2.matchLabels" . | indent 4 }}
    component: uiapp
{{- end }}
