{{- if .Values.aspspMock.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "psd2.fullname" . }}-mock-db
  labels:
{{ include "psd2.labels" . | indent 4 }}
    app: aspsp-mock
type: Opaque
data:
{{- range $name, $value := .Values.aspspMock.secrets }}
{{- if not (empty $value) }}
{{ $name }}: {{ tpl (toString $value) $ | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
