{{- if .Values.mock.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  {{- with .Values.mock.db.serviceAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
  name: "{{ template "psd2.fullname" . }}-mock-db"
  labels:
{{ include "psd2.labels" . | indent 4 }}
    app.kubernetes.io/component: mock-db
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: mongo
  selector:
{{ include "psd2.matchLabels" . | indent 4 }}
    app.kubernetes.io/component: mock-db
{{- end }}
