{{ if and .Values.cmsPortal.enabled (not .Values.cmsPortal.image.stream) }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ template "psd2.fullname" . }}-cmsportal
  labels:
{{ include "psd2.labels" . | indent 4 }}
    app.kubernetes.io/component: cmsPortal
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: {{ .Values.cmsPortal.image.name }}{{ eq (substr 0 1 .Values.cmsPortal.image.tag) "@" | ternary "" ":" }}{{ .Values.cmsPortal.image.tag }}
      referencePolicy:
        type: {{ .Values.pullThrough | ternary "Local" "Source" }}
{{- end }}
