{{ if and .Values.cms.enabled .Values.cms.route.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "psd2.fullname" . }}-cms
  labels:
{{ include "psd2.labels" . | indent 4 }}
    component: ConsentManagementSystem
spec:
  host: {{ tpl (required "cms.route.host must be defined" .Values.cms.route.host) . | quote }}
  port:
    targetPort: http
{{- with .Values.cms.route.tls }}
  tls:
{{ toYaml . | indent 4 }}
{{- end }}
  to:
    kind: Service
    name: {{ template "psd2.fullname" . }}-cms
    weight: 100
    wildcardPolicy: None
{{- end }}
