{{- if and .Values.keycloak.enabled (eq .Values.keycloak.dbVendor "postgres") }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
{{- with .Values.postgres.deploymentAnnotations }}
{{ toYaml . | indent 4 }}
{{- end }}
    image.openshift.io/triggers: |
      [{
        "from": {
          "kind": "ImageStreamTag",
          {{- if .Values.postgres.image.namespace }}
          "namespace": "{{ .Values.postgres.image.namespace }}",
          {{- end }}
          "name": "{{- if .Values.postgres.image.stream }}{{ .Values.postgres.image.name }}:{{ default "latest" .Values.postgres.image.tag }}{{- else }}{{ template "psd2.fullname" . }}-pg-db:latest{{- end }}"
        },
        "fieldPath": "spec.template.spec.containers[?(@.name==\"keycloak-db\")].image"
      }{{- if .Values.postgres.metrics.enabled }},{
        "from": {
          "kind": "ImageStreamTag",
          {{- if .Values.postgres.metrics.image.namespace }}
          "namespace": "{{ .Values.postgres.metrics.image.namespace }}",
          {{- end }}
          "name":"{{- if .Values.postgres.metrics.image.stream }}{{ .Values.postgres.metrics.image.name }}:{{ default "latest" .Values.postgres.metrics.image.tag }}{{- else }}{{ template "psd2.fullname" . }}-pg-metrics:latest{{- end }}"
        },
        "fieldPath": "spec.template.spec.containers[?(@.name==\"metrics\")].image"
      }{{- end }}]
  name: {{ template "psd2.fullname" . }}-keycloak-db
  labels:
{{ include "psd2.labels" . | indent 4 }}
    app.kubernetes.io/component: keycloak-db
spec:
  serviceName: {{ template "psd2.fullname" . }}-keycloak-db-hs
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
{{ include "psd2.matchLabels" . | indent 6 }}
      app.kubernetes.io/component: keycloak-db
  replicas: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/postgres/pg-secrets.yaml") . | sha256sum }}
{{- with .Values.postgres.podAnnotations }}
{{ toYaml . | indent 8 }}
{{- end }}
      labels:
{{ include "psd2.matchLabels" . | indent 8 }}
        app.kubernetes.io/component: keycloak-db
{{- with .Values.postgres.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: keycloak-db
        # redhat hack: invalid image to stop first unused deployment
        image: " "
        imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
        {{- if .Values.postgres.slave.enabled }}
        args: ["run-postgresql-master"]
        {{- end }}
        env:
        - name: TZ
          value: {{ .Values.timezone | quote }}
        {{- range $name, $value := .Values.postgres.secrets }}
        {{- if not ( empty $value) }}
        - name: {{ $name | quote }}
          valueFrom:
            secretKeyRef:
              name: {{ template "psd2.fullname" $ }}-pg-db
              key: {{ $name | quote }}
        {{- end }}
        {{- end }}
        ports:
        - name: postgresql
          containerPort: 5432
          protocol: TCP
        resources:
{{ toYaml .Values.postgres.resources | indent 10 }}
        livenessProbe:
{{ toYaml .Values.postgres.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.postgres.readinessProbe | indent 10 }}
        {{- if .Values.postgres.persistence.enabled }}
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: data
        {{- end }}
      {{- if .Values.postgres.metrics.enabled }}
      - name: metrics
        # redhat hack: invalid image to stop first unused deployment
        image: " "
        env:
        - name: DATA_SOURCE_URI
          value: localhost:5432/?sslmode=disable
        - name: DATA_SOURCE_USER
          value: postgres
        - name: DATA_SOURCE_PASS
          valueFrom:
            secretKeyRef:
              key: POSTGRESQL_ADMIN_PASSWORD
              name: {{ template "psd2.fullname" . }}-pg-db
        ports:
        - name: metrics
          containerPort: 9187
        {{- if .Values.postgres.metrics.customMetrics }}
        args: ["--extend.query-path", "/conf/custom-metrics.yaml"]
        volumeMounts:
          - name: custom-metrics
            mountPath: /conf
            readOnly: true
      {{- end }}
        resources:
{{ toYaml .Values.postgres.metrics.resources | indent 10 }}
{{- end }}
{{- if and .Values.postgres.metrics.enabled .Values.postgres.metrics.customMetrics }}
      volumes:
      - name: custom-metrics
        configMap:
          name: {{ template "psd2.fullname" . }}-postgresql-metrics
          defaultMode: 0555
{{- end }}
{{- if .Values.postgres.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
{{- if .Values.postgres.persistence.storageClass }}
      storageClassName: "{{ .Values.postgres.persistence.storageClass }}"
{{- end }}
      resources:
        requests:
          storage: {{ .Values.postgres.persistence.size }}
{{- end }}
{{- end }}
